/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ll_suporte;

import static com.mycompany.ll_suporte.tela_lista_chamados.id;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author felip
 */
public class tela_detalhe_chamado extends javax.swing.JFrame {
//Conexão com o banco
    int id_chamado = Integer.parseInt(id);
        Connection conexao = null;
        PreparedStatement statement = null;


        String url = "jdbc:mysql://localhost/ll_suporte";
        String usuario = "root";
        String senha = ""; // 154869
    /**
     * Creates new form tela_detalhe_chamado
     */
        
    public void detalhe_chamado(){
        //Fazendo o select de uma view e preenchendo os campos com o itens dessa view
        try {
            conexao = DriverManager.getConnection(url, usuario, senha);
            statement = conexao.prepareStatement("SELECT * FROM detalhe_chamado WHERE id_chamado = ? ;");
            statement.setInt(1, id_chamado);
            ResultSet resultado = statement.executeQuery();
            
            if (resultado.next()){
                try {
                    txtNumero.setText(resultado.getString("id_chamado"));
                    txtUsuario.setText(resultado.getString("nome_completo_cliente"));
                    cbGrupoAssunto.setSelectedItem(resultado.getString("grupo_chamado")); //GRUPO
                    txtTitulo.setText(resultado.getString("titulo_chamado"));
                    txtResponsavel.setText(resultado.getString("id_fun"));
                    txtAbertura.setText(resultado.getString("data_formatada"));
                    cbStatus.setSelectedItem(resultado.getString("status_chamado"));//STATUS
                    txtPrazo.setText(resultado.getString("prazo_chamado"));
                    cbPrioridade.setSelectedItem(resultado.getString("prioridade_chamado"));//PRIORIDADE
                    txtDescricao.setText(resultado.getString("descricao_chamado"));
                    txtSolucao.setText(resultado.getString("solucao_chamado"));
                } catch (SQLException ex) {
                    Logger.getLogger(tela_detalhe_chamado.class.getName()).log(Level.SEVERE, null, ex);
                }  
            }
            statement.execute();
        } catch (SQLException ex) {
            Logger.getLogger(tela_detalhe_chamado.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }
      
    public tela_detalhe_chamado() {
        initComponents();
    }
    public void detalhes_chamado (){
        
           
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbNomeDetalheChamado = new javax.swing.JLabel();
        lbNomeNumero = new javax.swing.JLabel();
        btnFechar = new javax.swing.JButton();
        lbNomeUsuario = new javax.swing.JLabel();
        lbGrupoAssunto = new javax.swing.JLabel();
        lbNomeTitulo = new javax.swing.JLabel();
        lbNomeResponsavel = new javax.swing.JLabel();
        lbNomeAbertura = new javax.swing.JLabel();
        lbNomeStatus = new javax.swing.JLabel();
        lbNomePrazo = new javax.swing.JLabel();
        lbNomePrioridade = new javax.swing.JLabel();
        txtResponsavel = new javax.swing.JTextField();
        txtAbertura = new javax.swing.JTextField();
        txtPrazo = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        txtUsuario = new javax.swing.JTextField();
        txtTitulo = new javax.swing.JTextField();
        lbNomeDescricao = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescricao = new javax.swing.JTextArea();
        cbStatus = new javax.swing.JComboBox<>();
        cbPrioridade = new javax.swing.JComboBox<>();
        cbGrupoAssunto = new javax.swing.JComboBox<>();
        lbNomeSolucao = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtSolucao = new javax.swing.JTextArea();
        btnSalvar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        lbNovoChamado = new javax.swing.JLabel();
        lbNovoColaborador = new javax.swing.JLabel();
        lbConsultar = new javax.swing.JLabel();
        lbNovoUsuario = new javax.swing.JLabel();
        lbNomeRelatorio = new javax.swing.JLabel();
        lbListaDeColaboradores = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        lbNomeMenu = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        lbLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(123, 150, 212));

        lbNomeDetalheChamado.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbNomeDetalheChamado.setText("DETALHES DO CHAMADO");

        lbNomeNumero.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbNomeNumero.setText("Número:");

        btnFechar.setBackground(new java.awt.Color(123, 150, 212));
        btnFechar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        lbNomeUsuario.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbNomeUsuario.setText("Nome Usuário:");

        lbGrupoAssunto.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbGrupoAssunto.setText("Grupo:");

        lbNomeTitulo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbNomeTitulo.setText("Título:");

        lbNomeResponsavel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbNomeResponsavel.setText("Responsável:");

        lbNomeAbertura.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbNomeAbertura.setText("Abertura:");

        lbNomeStatus.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbNomeStatus.setText("Status:");

        lbNomePrazo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbNomePrazo.setText("Prazo:");

        lbNomePrioridade.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbNomePrioridade.setText("Prioridade:");

        txtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroActionPerformed(evt);
            }
        });

        lbNomeDescricao.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbNomeDescricao.setText("Descrição:");

        txtDescricao.setColumns(20);
        txtDescricao.setRows(5);
        jScrollPane1.setViewportView(txtDescricao);

        cbStatus.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Novo", "Em análise", "Em andamento", "Resolvido", "Encerrado", "Cancelado" }));

        cbPrioridade.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cbPrioridade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baixo", "Médio", "Alto" }));

        cbGrupoAssunto.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cbGrupoAssunto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "HARDWARE", "SERVIÇOS DE TI", "REDES", "SOFTWARE", "ACESSO" }));
        cbGrupoAssunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGrupoAssuntoActionPerformed(evt);
            }
        });

        lbNomeSolucao.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbNomeSolucao.setText("Solução:");

        txtSolucao.setColumns(20);
        txtSolucao.setRows(5);
        jScrollPane2.setViewportView(txtSolucao);

        btnSalvar.setBackground(new java.awt.Color(123, 150, 212));
        btnSalvar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnEditar.setBackground(new java.awt.Color(123, 150, 212));
        btnEditar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(24, 24, 24)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lbGrupoAssunto)
                                        .addComponent(lbNomeUsuario)
                                        .addComponent(lbNomeTitulo)
                                        .addComponent(lbNomeDescricao)
                                        .addComponent(lbNomeSolucao))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtTitulo)
                                        .addComponent(txtUsuario)
                                        .addComponent(txtNumero)
                                        .addComponent(cbGrupoAssunto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(lbNomeNumero))
                            .addGap(123, 123, 123)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbNomeResponsavel)
                                .addComponent(lbNomeAbertura)
                                .addComponent(lbNomeStatus)
                                .addComponent(lbNomePrazo)
                                .addComponent(lbNomePrioridade))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtAbertura, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtResponsavel, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtPrazo)
                                .addComponent(cbStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbPrioridade, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(36, 36, 36)
                            .addComponent(lbNomeDetalheChamado))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(39, 39, 39)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnEditar)
                                .addGap(18, 18, 18)
                                .addComponent(btnSalvar)
                                .addGap(18, 18, 18)
                                .addComponent(btnFechar)
                                .addGap(13, 13, 13))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbNomeDetalheChamado)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNomeNumero)
                    .addComponent(lbNomeResponsavel)
                    .addComponent(txtResponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNomeUsuario)
                    .addComponent(lbNomeAbertura)
                    .addComponent(txtAbertura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbGrupoAssunto)
                    .addComponent(lbNomeStatus)
                    .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbGrupoAssunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNomeTitulo)
                    .addComponent(lbNomePrazo)
                    .addComponent(txtPrazo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNomeDescricao)
                    .addComponent(lbNomePrioridade)
                    .addComponent(cbPrioridade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbNomeSolucao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEditar)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnFechar)
                        .addComponent(btnSalvar)))
                .addGap(13, 13, 13))
        );

        lbNovoChamado.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbNovoChamado.setText("NOVO CHAMADO");
        lbNovoChamado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbNovoChamadoMouseClicked(evt);
            }
        });

        lbNovoColaborador.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbNovoColaborador.setText("NOVO COLABORADOR");
        lbNovoColaborador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbNovoColaboradorMouseClicked(evt);
            }
        });

        lbConsultar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbConsultar.setText("CONSULTAR");
        lbConsultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbConsultarMouseClicked(evt);
            }
        });

        lbNovoUsuario.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbNovoUsuario.setText("NOVO USUARIO");
        lbNovoUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbNovoUsuarioMouseClicked(evt);
            }
        });

        lbNomeRelatorio.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbNomeRelatorio.setText("RELATÓRIOS");
        lbNomeRelatorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbNomeRelatorioMouseClicked(evt);
            }
        });

        lbListaDeColaboradores.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbListaDeColaboradores.setText("LISTA DE COLABORADORES");
        lbListaDeColaboradores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbListaDeColaboradoresMouseClicked(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator10.setForeground(new java.awt.Color(0, 0, 0));

        lbNomeMenu.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbNomeMenu.setText("MENU");
        lbNomeMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbNomeMenuMouseClicked(evt);
            }
        });

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));

        lbLogo.setIcon(new javax.swing.ImageIcon("D:\\Users\\MDEOLINDO\\Desktop\\PROG_APP_GIT\\sistema_chamado\\LL_SUPORTE\\src\\main\\java\\com\\mycompany\\ll_suporte\\imagem\\logo canto superior.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(lbNomeMenu))
                            .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbNovoColaborador)
                        .addGap(44, 44, 44)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator5)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator3)
                    .addComponent(jSeparator6)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbListaDeColaboradores)
                        .addGap(11, 11, 11))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbLogo))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(lbNovoChamado))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbNomeRelatorio)
                                    .addComponent(lbNovoUsuario)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(lbConsultar))
                            .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(779, 779, 779))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(lbLogo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)))
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbNovoChamado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbNovoUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbNovoColaborador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbNomeRelatorio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbConsultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbListaDeColaboradores)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator10, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbNomeMenu)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lbNovoChamadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbNovoChamadoMouseClicked
        // TODO add your handling code here:
        tela_detalhe_chamado.this.dispose();
        tela_abertura_chamados lbNovoChamado = new tela_abertura_chamados();
        lbNovoChamado.setVisible(true);
    }//GEN-LAST:event_lbNovoChamadoMouseClicked

    private void lbNovoColaboradorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbNovoColaboradorMouseClicked
        // TODO add your handling code here:
        tela_detalhe_chamado.this.dispose();
        tela_cadastro_colaborador lbNovoColaborador = new tela_cadastro_colaborador();
        lbNovoColaborador.setVisible(true);
    }//GEN-LAST:event_lbNovoColaboradorMouseClicked

    private void lbConsultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbConsultarMouseClicked
        // TODO add your handling code here:
        tela_detalhe_chamado.this.dispose();
        tela_lista_chamados lbConsultar = new tela_lista_chamados();
        lbConsultar.setVisible(true);
    }//GEN-LAST:event_lbConsultarMouseClicked

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        // TODO add your handling code here:
        tela_detalhe_chamado.this.dispose();
        tela_lista_chamados btnFechar = new tela_lista_chamados();
        btnFechar.setVisible(true);
    }//GEN-LAST:event_btnFecharActionPerformed

    private void lbNovoUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbNovoUsuarioMouseClicked
        // TODO add your handling code here:
        tela_detalhe_chamado.this.dispose();
        tela_cadastro_usuario lbNovoUsuario = new tela_cadastro_usuario();
        lbNovoUsuario.setVisible(true);
    }//GEN-LAST:event_lbNovoUsuarioMouseClicked

    private void lbNomeMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbNomeMenuMouseClicked
        tela_detalhe_chamado.this.dispose();
        tela_menu_rapido lbNomeSair = new tela_menu_rapido();
        lbNomeSair.setVisible(true);


        // TODO add your handling code here:
    }//GEN-LAST:event_lbNomeMenuMouseClicked

    private void lbListaDeColaboradoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbListaDeColaboradoresMouseClicked
        // TODO add your handling code here:
        tela_detalhe_chamado.this.dispose();
        tela_lista_colaborador lbListaDeColaboradores = new tela_lista_colaborador();
        lbListaDeColaboradores.setVisible(true);
        
    }//GEN-LAST:event_lbListaDeColaboradoresMouseClicked

    private void lbNomeRelatorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbNomeRelatorioMouseClicked
        // TODO add your handling code here:
        tela_detalhe_chamado.this.dispose();
        tela_relatorio lbNomeRelatorio = new tela_relatorio();
        lbNomeRelatorio.setVisible(true);
    }//GEN-LAST:event_lbNomeRelatorioMouseClicked

    private void cbGrupoAssuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGrupoAssuntoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbGrupoAssuntoActionPerformed

    private void txtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroActionPerformed

// TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // Desabilitando as edições dos campos ao abrir a tela
        detalhe_chamado();
        txtNumero.setEnabled(false);
        txtUsuario.setEnabled(false);
        txtTitulo.setEnabled(false);
        txtResponsavel.setEnabled(false);
        txtAbertura.setEnabled(false);
        txtPrazo.setEnabled(false);
        txtDescricao.setEnabled(false);
        txtSolucao.setEnabled(false);
        btnSalvar.setEnabled(false);
        cbGrupoAssunto.setEnabled(false);
        cbStatus.setEnabled(false);
        cbPrioridade.setEnabled(false);
    }//GEN-LAST:event_formWindowOpened

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // Habilitando as edições dos campos ao clicar no botão Editar
        txtUsuario.setEnabled(true);
        txtTitulo.setEnabled(true);
        txtResponsavel.setEnabled(true);
        //txtAbertura.setEnabled(true);
        txtPrazo.setEnabled(true);
        txtDescricao.setEnabled(true);
        txtSolucao.setEnabled(true);
        btnSalvar.setEnabled(true);
        cbGrupoAssunto.setEnabled(true);
        cbStatus.setEnabled(true);
        cbPrioridade.setEnabled(true);
        
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        try {
           //Atualizando os campos da tabela chamado ao clicar no botao salvar          
            String sql = "UPDATE chamado SET  titulo_chamado = ?, id_fun = ?, grupo_chamado = ?, status_chamado = ?, data_abertura_chamado = ?,"
                    + "prioridade_chamado = ?, prazo_chamado = ?, descricao_chamado = ?, solucao_chamado = ? WHERE id_chamado = ?";
        
            statement = conexao.prepareStatement(sql);
            String dia = txtAbertura.getText().substring(0,2);
            String mes = txtAbertura.getText().substring(3,5);
            String ano = txtAbertura.getText().substring(6);
            String data = ano +"-"+mes+"-"+dia;
            String grupo = (String) cbGrupoAssunto.getSelectedItem();
            String status = (String) cbStatus.getSelectedItem();
            String prioridade = (String) cbPrioridade.getSelectedItem();
            statement.setString(1, txtTitulo.getText()); // titulo_chamado
            statement.setString(2, txtResponsavel.getText()); // id_fun
            statement.setString(3, grupo); //GRUPO
            statement.setString(4, status);//status
            statement.setString(5, data); // data_abertura_chamado
            statement.setString(6, prioridade); //prioridade
            statement.setString(7, txtPrazo.getText()); // prazo_chamado
            statement.setString(8, txtDescricao.getText()); // descricao_chamado
            statement.setString(9, txtSolucao.getText()); // solucao_chamado
            statement.setInt(10, Integer.parseInt(txtNumero.getText())); // id_chamado
            statement.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Alterações salvas com sucesso!");
        } catch (SQLException ex) {
            Logger.getLogger(tela_detalhe_chamado.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tela_detalhe_chamado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tela_detalhe_chamado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tela_detalhe_chamado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tela_detalhe_chamado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tela_detalhe_chamado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbGrupoAssunto;
    private javax.swing.JComboBox<String> cbPrioridade;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JLabel lbConsultar;
    private javax.swing.JLabel lbGrupoAssunto;
    private javax.swing.JLabel lbListaDeColaboradores;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JLabel lbNomeAbertura;
    private javax.swing.JLabel lbNomeDescricao;
    private javax.swing.JLabel lbNomeDetalheChamado;
    private javax.swing.JLabel lbNomeMenu;
    private javax.swing.JLabel lbNomeNumero;
    private javax.swing.JLabel lbNomePrazo;
    private javax.swing.JLabel lbNomePrioridade;
    private javax.swing.JLabel lbNomeRelatorio;
    private javax.swing.JLabel lbNomeResponsavel;
    private javax.swing.JLabel lbNomeSolucao;
    private javax.swing.JLabel lbNomeStatus;
    private javax.swing.JLabel lbNomeTitulo;
    private javax.swing.JLabel lbNomeUsuario;
    private javax.swing.JLabel lbNovoChamado;
    private javax.swing.JLabel lbNovoColaborador;
    private javax.swing.JLabel lbNovoUsuario;
    private javax.swing.JTextField txtAbertura;
    private javax.swing.JTextArea txtDescricao;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtPrazo;
    private javax.swing.JTextField txtResponsavel;
    private javax.swing.JTextArea txtSolucao;
    private javax.swing.JTextField txtTitulo;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
